events{
	worker_connections 1024;
}

http{
	upstream rustfs_backend{
		server rustfs:9000;
	}

	server{
		* listen for incoming http request on port 80, which is the standard convention for "http" traffic *
		listen 80;

		server_name localhost;

		* responds to all incoming http requests with a 301 redirect to the same URL but with the "https" scheme, 
		* effectively forcing all traffic to use SSL/TLS encryption
		* $host -> example.com, $request_uri -> /path/to/resource?query=string
		return 301 https://$host$request_uri;
			
	server{
		* connects to the backend server over port 443, which is the standard port for "https" traffic *
		listen 443 ssl;

		server_name localhost;

		* After establishing a TCP connection, the server presents its SSL certificate to the client to prove its identity, the browser then verifies the certificate against its list of 
		trusted certificate authorities (CAs) to ensure that it is valid and has not been tampered with *
		ssl_certificate/etc/ssl/certs/fullchain.pem;

		* The browser and server then perform a key exchange by mathematically deriving a shared secret key that will be used to encrypt and decrypt the data sent between them *
		ssl_certificate_key /etc/nginx/certs/key.pem;

		location / {
			proxy_pass http://rustfs_backend;

			* perserves or add HTTP headers before fowarding request, the original host header 
			* is passed to the backend, serves the domain used by the client, instead of the hostname e.g. backend:8000
			proxy_set_header Host $host;
			
			* appends the current proxy, where X-fowarded-For is the entire proxy chain
			proxy_set_header X-Real-IP $remote_addr;
			
			* timestamp
			proxy_set_header X-Amz-Date $http_x_amz_date;
			proxy_set_header Authorization $http_authorization;
			
			* hash of the received payload, which is used to verify the integrity of the request body and ensure that it has not been tampered with during transmission
			proxy_set_header X-Amz-Content-Sha256 $http_x_amz_content_sha256;

			
			* append client's ip adderess to the "X-Forwarded-For" header, which is used for identifying the originating IP address of a client connecting to a web server *
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			
			* set the "X-Forwarded-Proto" header to the scheme of the original request (http or https), which is useful when SSL is terminated at NGINX. *
			proxy_set_header X-Forwarded-Proto $scheme;
		}
	}